# SPDX-FileCopyrightText: 2024 Mika Tammi
# SPDX-License-Identifier: MIT

name: check

on:
  pull_request:
    branches:
      - master

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v25
      - name: Check .nix formatting
        run: nix fmt -- --fail-on-change
      - name: Check reuse lint
        run: nix develop --command reuse lint
      - name: Check nix flake show runs successfully
        run: nix flake show
      - name: Run nix flake check
        run: nix flake check
